org.gnome.EvolutionEws.Devel.json: Revert change of the "branch" name
CI fails with:

    error: Refspec 'app/org.gnome.EvolutionEws.Devel/x86_64/master' not found

when it's "gnome-47".